export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SELECTED_ALL = 'SELECTED_ALL';
export const SELECTED_EACH = 'SELECTED_EACH';


export const FETCH_OVERVIEW = 'FETCH_OVERVIEW';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const SELECT_COMPANY = 'SELECT_COMPANY';
export const TOGGLE_CREATE_COMPANY = 'TOGGLE_CREATE_COMPANY';
